force-app/main/default/objects/Opportunity/fields/Excercise_plan__c.field-meta.xml
<CustomField>
    <fullName>Excercise_plan__c</fullName>
    <inlineHelpText>Here is the patient&apos;s excercise plan</inlineHelpText>
    <label>Excercise plan</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Food_plan__c.field-meta.xml
<CustomField>
    <fullName>Food_plan__c</fullName>
    <inlineHelpText>Here is the actual food plan of the patient</inlineHelpText>
    <label>Food plan</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <inlineHelpText>Patient&apos;s actual height</inlineHelpText>
    <label>Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IMC__c.field-meta.xml
<CustomField>
    <fullName>IMC__c</fullName>
    <formula>( Weigh__c ) / ( Height__c ^ 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Below 18.5   --&gt; Low weight
18.5 - 24.9  --&gt; Normal
25.0 -29.9   --&gt; Excess weight
30.0 or more --&gt;  Obesity</inlineHelpText>
    <label>IMC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Weigh__c.field-meta.xml
<CustomField>
    <fullName>Weigh__c</fullName>
    <inlineHelpText>Insert the actual weigh</inlineHelpText>
    <label>Weigh</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/YN_PlanDiet.cls
/**
 * @description       : 
 * @author            : aahamjik
 * @group             : 
 * @last modified on  : 03-03-2022
 * @last modified by  : aahamjik
**/
public with sharing class YN_PlanDiet {

    @AuraEnabled(cacheable=true)
    public static String getOpenOpportunity(String userId){
        System.debug('S user:'+userId);
         User user=null;
        // //Opportunity planDiet=null;
        // try {
             user=[Select Id, AccountId from User where id=:userId limit 1 ];
        //     System.debug('user:'+user);
         Opportunity planDiet=[Select Id,Name, Weigh__c,Height__c, IMC__c,Excercise_plan__c, Food_plan__c from Opportunity where AccountId =:user.AccountId and IsClosed =false Limit 1];
            System.debug('plan'+planDiet);
        // } catch (Exception e) {
        //     System.debug('msg'+e.getMessage());
        // }
         String s=JSON.serialize('s'+planDiet);
         System.debug('p:'+s);
         
        return s;
    }
}